### ISSUE TITLE
Annotation multi-selector unreliable? 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/Apelles#8]
Stops working once in a while. Will have to verify its functions. 
Details here: https://github.com/davidstutz/bootstrap-multiselect/issues/892

**Comment by bhargav** [comment]
Brat loads its own version of jQuery which is very old. So there might be a conflict in namespaces. It never worked for me. Did it work for you anytime?

**Comment by danyaljj** [comment]
Good point. It was working for me this working, but it doesn't seem functional now. Not sure what's going on.
